<?xml version="1.0" encoding="UTF- 8"?>
<!DOCTYPE sistemaSolar [
    <!ELEMENT sistemaSolar
  (cuerpo*)>
    <!ELEMENT cuerpo ((planeta|
  satelite|asteroide)+)>
    <!ELEMENT planeta (#PCDATA)>
    <!ELEMENT satelite (#PCDATA)>
    <!ELEMENT asteroide (#PCDATA)>]>
    <cuerpo>
        <planeta>Tierra</planeta>
        <satelite>Luna</satelite>
      </cuerpo>
      <asteroide>Ceres</asteroide>
    </sistemaSolar>
    